/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChangeLogDialog: typeof import('./components/ChangeLogDialog.vue')['default']
    ConsoleDialog: typeof import('./components/ConsoleDialog.vue')['default']
    DialogTitle: typeof import('./components/DialogTitle.vue')['default']
    FaqGroup: typeof import('./components/FaqGroup.vue')['default']
    MarkdownContentBox: typeof import('./components/MarkdownContentBox.vue')['default']
    NewVersionDialog: typeof import('./components/NewVersionDialog.vue')['default']
    OtherLinkItem: typeof import('./components/OtherLinkItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimplePage: typeof import('./components/SimplePage.vue')['default']
    SpeedDial: typeof import('./components/SpeedDial.vue')['default']
    YuzuSaveCommonPart: typeof import('./components/YuzuSaveCommonPart.vue')['default']
    YuzuSaveRestoreTab: typeof import('./components/YuzuSaveRestoreTab.vue')['default']
  }
}
