/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/faq': RouteRecordInfo<'/faq', '/faq', Record<never, never>, Record<never, never>>,
    '/keys': RouteRecordInfo<'/keys', '/keys', Record<never, never>, Record<never, never>>,
    '/otherLinks': RouteRecordInfo<'/otherLinks', '/otherLinks', Record<never, never>, Record<never, never>>,
    '/ryujinx': RouteRecordInfo<'/ryujinx', '/ryujinx', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/suyu': RouteRecordInfo<'/suyu', '/suyu', Record<never, never>, Record<never, never>>,
    '/yuzu': RouteRecordInfo<'/yuzu', '/yuzu', Record<never, never>, Record<never, never>>,
    '/yuzuCheatsManagement': RouteRecordInfo<'/yuzuCheatsManagement', '/yuzuCheatsManagement', Record<never, never>, Record<never, never>>,
    '/yuzuSaveManagement': RouteRecordInfo<'/yuzuSaveManagement', '/yuzuSaveManagement', Record<never, never>, Record<never, never>>,
  }
}
