name: Manual build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Run yarn install
      uses: borales/actions-yarn@v5
      with:
        dir: vue3
        cmd: install
    - name: Run yarn build
      uses: borales/actions-yarn@v5
      with:
        dir: vue3
        cmd: build
    - run: |
        python -m venv venv
        venv\Scripts\activate.ps1
        pip install poetry
        poetry install
        poetry run pyinstaller --noconfirm --onefile --windowed --icon "./web/favicon.ico" --add-data "./module/*.exe;./module/" --add-data "./web;web/" --additional-hooks-dir=".\\hooks" "./main_devnull.py" --name "NsEmuTools"
    - uses: actions/upload-artifact@v4
      with:
        path: dist/*
        name: NsEmuTools
