name: Manual build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - uses: oven-sh/setup-bun@v2
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: src-tauri
    - name: Install frontend dependencies
      working-directory: frontend
      run: bun install
    - name: Build frontend
      working-directory: frontend
      run: bun run build
    - name: Build Rust executable
      run: cargo build --manifest-path src-tauri/Cargo.toml --release --locked --bin NsEmuTools
    - uses: actions/upload-artifact@v4
      with:
        path: src-tauri/target/release/NsEmuTools.exe
        name: NsEmuTools-windows-exe
        if-no-files-found: error
