name: Release notify

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install requests
      - name: run send_release_notify.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TG_SEND_TO: ${{ secrets.TELEGRAM_TO }}
        run: |
          python send_release_notify.py
